#APPLICATION
## LOG
logging:
  level:
    org.springframework.security: WARN
    io.saagie: WARN
    me.ramswaroop.jbot: WARN
## GENERAL
url: ${CROISSANTS_URL}
opsEmail: ${CROISSANTS_OPS_MAIL}
# SLACK BOT
slackBotToken: ${CROISSANTS_SLACKBOT_TOKEN}
slackWebhookUrl: ${CROISSANTS_SLACK_WEBHOOK_URL}
rtmUrl: "https://slack.com/api/rtm.start?token={token}&simple_latest&no_unreads"
# MAIL
sendEmail: false
mailFrom: ${CROISSANTS_MAIL_FROM:no@reply.com}
security:
  basic:
    enabled: false
spring:
  mail:
    host: ${CROISSANTS_MAIL_HOST:localhost}
    port: ${CROISSANTS_MAIL_PORT:25}
    username: ${CROISSANTS_MAIL_USERNAME:admin}
    password: ${CROISSANTS_MAIL_PASSWORD:password}
    protocol: smtp
    properties:
          mail:
            smtp:
              starttls:
                enable: false
              auth: false
              connectiontimeout: 5000
              timeout: 5000
              writetimeout: 5000
  datasource:
    url: ${CROISSANTS_MYSQL_URI}
    username: ${CROISSANTS_MYSQL_USER}
    password: ${CROISSANTS_MYSQL_PASS}
  jpa:
    hibernate:
      ddl-auto: update
# MONGO
#  data:
#    mongodb:
#      uri: mongodb://${CROISSANTS_MONGO_URI}
##########################
# SECURITY
slack:
  client:
    clientId: ${CROISSANTS_CLIENTID}
    clientSecret: ${CROISSANTS_CLIENTSECRET}
    accessTokenUri: https://slack.com/api/oauth.access
    userAuthorizationUri: https://slack.com/oauth/authorize
    tokenName: token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: identity.basic,identity.email,identity.avatar,identity.team
  resource:
    userInfoUri: https://slack.com/api/users.identity?token=
